### ISSUE TITLE
Implement %ASA-3-114018: Failed to set port speed in 4GE SSM I/O card (error error_string).

### ISSUE THREAD

**Issue by taismith123** [NCATComp410/comp410_spring_2021#21]
Requirement is to split up this message type into the following fields (columns)

Type == ASA
Severity == 3
ID == 114018
Text = Failed to set port speed in 4GE SSM I/O card
Error = error_string

**Comment by claesmk** [comment]
Looks good let me know if you need any help with the regex for the (error error_string) parsing

**Comment by taismith123** [comment]
Hello @claesmk, when I run "pytests in test" for the first time I receive this error
message:

init_dgelsd failed init

Error
Traceback (most recent call last):
  File
"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/case.py",
line 59, in testPartExecutor
    yield
  File
"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/case.py",
line 593, in run
    self._callTestMethod(testMethod)
  File
"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/case.py",
line 550, in _callTestMethod
    method()
  File
"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py",
line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_log_parse
Traceback (most recent call last):
  File
"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py",
line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File
"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py",
line 377, in _get_module_from_name
    __import__(name)
  File
"/Users/taismith/Documents/comp410_spring_2021/id_pkg/test/test_log_parse.py",
line 3, in <module>
    import id_pkg as intrusion_detect
  File "/Users/taismith/Documents/comp410_spring_2021/id_pkg/__init__.py",
line 1, in <module>
    from .src.log_parse import LogParse
  File
"/Users/taismith/Documents/comp410_spring_2021/id_pkg/src/log_parse.py",
line 1, in <module>
    import pandas as pd
  File
"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/__init__.py",
line 11, in <module>
    __import__(dependency)
  File
"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/__init__.py",
line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to
using a buggy Accelerate backend. If you compiled yourself, see
site.cfg.example for information. Otherwise report this to the vendor that
provided NumPy.
RankWarning: Polyfit may be poorly conditioned




Assertion failed

Assertion failed


Ran 1 test in 0.015s

FAILED (errors=1)

Process finished with exit code 1

Assertion failed

Assertion failed

-Earlier I had to manually install pandas. I can't seem to resolve this
issue.?

**Comment by claesmk** [comment]
Is this on Windows or a Mac? Did you use conda to install your requirements or pip?

**Comment by taismith123** [comment]
@claesmk 
I am on a Mac and I believe I used conda.

**Comment by claesmk** [comment]
I think I'd first try creating a new virtual env and see if that fixes the issue.  Open a terminal window and cd to your repo clone.  Then follow these steps:

```
conda create --name py39_2 python=3.9
conda activate py39_2
conda install --file requirements.txt
conda install pytest-cov
```

Then try your unit tests
```
pytest --cov=id_pkg
```

I verified these steps work on my Mac, but, I have never seen this error. If this works, then you should start using this new virtual env instead of your old one.  If this doesn't work you might need to try uninstalling and reinstalling numpy

**Comment by taismith123** [comment]
@claesmk 
I have tried all of the steps above (including uninstalling and reinstalling numpy) and I am sadly still getting the same error message. Should I delete the repo and start over?

**Comment by claesmk** [comment]
I don't think it's your repo - please try this (using pip instead of conda)
```
pip uninstall numpy
pip install numpy
```
If that doesn't work I think you'll need to drop down to python 3.8 and try that.
