### ISSUE TITLE
Implement %ASA-3-114019: Failed to set media type in 4GE SSM I/O card (error error_string).

### ISSUE THREAD

**Issue by ereewa3** [NCATComp410/comp410_spring_2021#22]
Requirement is to split up this message type into the following fields:

Type == ASA
Severity==3
ID==114019
Text=Failed to set media type in 4GE SSM I/O card (error error_string).
Error= error_string

**Comment by claesmk** [comment]
This looks good.  If you are using a PC please check out [this](https://github.com/orgs/NCATComp410/teams/comp410spring2021class/discussions/2) post.
