### ISSUE TITLE
Implement %ASA-3-114006: Failed to get port statistics in 4GE SSM I/O card (error error_string).

### ISSUE THREAD

**Issue by lancenonce** [NCATComp410/comp410_spring_2021#23]
Requirement is to split up this message type into the following fields (columns):

Type == ASA
Severity == 3
ID == 114006
Text = Failed to get port statistics in 4GE SSM I/O card
Error = error_string

**Comment by lancenonce** [comment]
@claesmk Hi Mr. Claes, when I try to run my test I get this error:

Failure
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/Users/lancedavis/PycharmProjects/comp410_spring_2021/id_pkg/test/test_log_parse.py", line 69, in test_parse_syslog_file
    self.assertTrue(df.loc[114006, 'Text'] == 'Failed to get port statistics in 4GE SSM I/O card')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 765, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

**The error occured after I added this code:** 
self.assertTrue(df.loc[114006, 'Type'] == 'ASA')
        # actual, expected
        self.assertEqual(df.loc[114006, 'Severity'], 3)
        self.assertTrue(df.loc[114006, 'Text'] == 'Failed to get port statistics in 4GE SSM I/O card')

I'm not sure what's going on, do you have any ideas?

**Comment by claesmk** [comment]
Try changing this:
```
self.assertTrue(df.loc[114006, 'Text'] == 'Failed to get port statistics in 4GE SSM I/O card')
```
to this:
```
self.assertEqual('Failed to get port statistics in 4GE SSM I/O card', df.loc[114006, 'Text'])
```
Then you should be able to see why the expected value does not equal what is actually saved.

Looking over your requirements:
```
Type == ASA
Severity == 3
ID == 114006
Text = Failed to get port statistics in 4GE SSM I/O card
Error = error_string
```
I think Text should really be
```
Text = Failed to get port statistics in 4GE SSM I/O card (error error_string).
```
And this is probably why you can't get your test case to pass. Try this and let me know how it goes.

**Comment by lancenonce** [comment]
Hey Mr. Claes,

I did that and I do think some things were resolved, but I'm still failing
the first test with this error:

Error
Traceback (most recent call last):
  File
"/Users/lancedavis/PycharmProjects/comp410_spring_2021/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py",
line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in
pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in
pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in
pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in
pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Error'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py",
line 60, in testPartExecutor
    yield
  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py",
line 676, in run
    self._callTestMethod(testMethod)
  File
"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py",
line 633, in _callTestMethod
    method()
  File
"/Users/lancedavis/PycharmProjects/comp410_spring_2021/id_pkg/test/test_log_parse.py",
line 70, in test_parse_syslog_file
    self.assertEqual(df.loc[114006, 'Error'], 'error_string')
  File
"/Users/lancedavis/PycharmProjects/comp410_spring_2021/venv/lib/python3.8/site-packages/pandas/core/indexing.py",
line 889, in __getitem__
    return self._getitem_tuple(key)
  File
"/Users/lancedavis/PycharmProjects/comp410_spring_2021/venv/lib/python3.8/site-packages/pandas/core/indexing.py",
line 1060, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File
"/Users/lancedavis/PycharmProjects/comp410_spring_2021/venv/lib/python3.8/site-packages/pandas/core/indexing.py",
line 831, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
  File
"/Users/lancedavis/PycharmProjects/comp410_spring_2021/venv/lib/python3.8/site-packages/pandas/core/indexing.py",
line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File
"/Users/lancedavis/PycharmProjects/comp410_spring_2021/venv/lib/python3.8/site-packages/pandas/core/indexing.py",
line 1124, in _getitem_axis
    return self._get_label(key, axis=axis)
  File
"/Users/lancedavis/PycharmProjects/comp410_spring_2021/venv/lib/python3.8/site-packages/pandas/core/indexing.py",
line 1073, in _get_label
    return self.obj.xs(label, axis=axis)
  File
"/Users/lancedavis/PycharmProjects/comp410_spring_2021/venv/lib/python3.8/site-packages/pandas/core/generic.py",
line 3738, in xs
    loc = index.get_loc(key)
  File
"/Users/lancedavis/PycharmProjects/comp410_spring_2021/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py",
line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'Error'

I think that something is wrong with my 'Error' line:

self.assertEqual(df.loc[114006, 'Error'], 'error_string')

Lance N. Davis

**Comment by lancenonce** [comment]
I tried switching the expected and actual values, nothing happened. I think
it may be something deeper in the code.

Lance N. Davis

**Comment by claesmk** [comment]
It looks like df.loc[114006, 'Error'] has not been set in log_parse.py - you should have code similar to this [pull request](https://github.com/NCATComp410/comp410_spring_2021/commit/d09d7dfdb5847463b36fe62b4e13af7fc4382ca1).  The key is:

```
            m = re.search(r' error (\w+)', df.loc[id, 'Text'])
             if m:
                 df.loc[id, 'Error'] = m.group(1)
```

**Comment by lancenonce** [comment]
Mr. Claes, I believe we have the same code and I'm getting the same error.
Here's my code:

# %ASA-3-114006: Failed to get port statistics in 4GE SSM I/O card
(error error_string)
if id == 114006:
    m = re.search(r' error (\w+)', df.loc[id, 'Text'])
    if m:

        df.loc[id, 'Error'] = m.group(1)

Lance N. Davis

**Comment by jttran15** [comment]
In your re.search() function, remove the space between r' and error. It should look something like this:
m = re.search(r'error (\w+)', df.loc[id, 'Text'])
To get a more exact search, you should include the parentheses for your (error error_string).

**Comment by lancenonce** [comment]
Thank you so much! It worked!

Lance N. Davis

**Comment by lancenonce** [comment]
#33

**Comment by lndavis6** [comment]
#34

**Comment by lancenonce** [comment]
#35
