### ISSUE TITLE
Implement - %ASA-1-114001: Failed to initialize 4GE SSM I/O card (error error_string).

### ISSUE THREAD

**Issue by jttran15** [NCATComp410/comp410_spring_2021#25]
Requirement is to split up this message type into the following fields (columns):

Type == ASA
Severity == 1
ID == 114001
Text = Failed to initialize 4GE SSM I/O card (error error_string)
Error = error_string

**Comment by claesmk** [comment]
Looks good so far.  If you are using a PC please check out [this](https://github.com/orgs/NCATComp410/teams/comp410spring2021class/discussions/2) post

**Comment by jttran15** [comment]
#26

**Comment by claesmk** [comment]
Your implementation works fine, however, you might consider changing your regex to look something like this which which causes a stronger match and guarantees you'll get exactly what you want:
```
        if id == 114001:
            # %ASA-1-114001: Failed to initialize 4GE SSM I/O card (error error_string)
            x = re.search(r' \(error (\w+)\)', df.loc[id, 'Text'])
            if x:
                df.loc[id, 'Error'] = x.group(1)
```
