### ISSUE TITLE
Team NULL: Implement suspicious ICMP packet detection (%ASA-4-313004)

### ISSUE THREAD

**Issue by rdungan** [NCATComp410/comp410_spring_2021#62]
Implement detection for ICMP Attack (icmp-drop) - Suspicious ICMP packets. 

%ASA-4-313004: Denied ICMP type=icmp_type, from source_address on interface interface_name to dest_address:no matching session

Information on this type of attack here: https://www.cloudflare.com/learning/ddos/ping-icmp-flood-ddos-attack/

**Comment by claesmk** [comment]
I corrected a couple of issues with this [commit](https://github.com/NCATComp410/comp410_spring_2021/commit/cef8252c0a7bea4b52d012a803074d1e3c04e324) - please take a look

**Comment by rdungan** [comment]
Thanks Mike, I was wondering what the best way to do ICMP type was, and if my regex was correct. I appreciate your help/edits!
