### ISSUE TITLE
Implementing ICMP Attack Detection 

### ISSUE THREAD

**Issue by taismith123** [NCATComp410/comp410_spring_2021#69]
**Here is a link that explains ICMP attacks:** [https://www.juniper.net/documentation/en_US/junos/topics/topic-map/security-icmp-sync-fragment-attack.html](url)

Implement detection for %ASA-3-313008: Denied ICMPv6 type=number , code=code from IP_address on interface interface_name.

**Comment by taismith123** [comment]
Hello @claesmk, are you available for office hours right now? I am having trouble with my environment again.

**Comment by claesmk** [comment]
Hi, sorry I missed this message, Dr Hinton and I were on the office hours Zoom until about 7:15.  Do you have time tomorrow?

**Comment by taismith123** [comment]
> Hi, sorry I missed this message, Dr Hinton and I were on the office hours Zoom until about 7:15. Do you have time tomorrow?

Yes! I am free after 4PM EST.

**Comment by claesmk** [comment]
OK - after 5pm will work for me will get a zoom link later

**Comment by taismith123** [comment]
Hello @claesmk, do you have any ideas as to why I would be getting this error? It's not recognizing the keywords for my parser in my test file. 
![Screen Shot 2021-03-27 at 1 28 00 PM](https://user-images.githubusercontent.com/42554501/112728994-4e380c00-8f00-11eb-8eec-722f73d48e62.png)

**Comment by claesmk** [comment]
Hi if you can push the code you have so far to your fork I'll take a look
at it.

It's likely because the Source column isn't getting parsed correctly for
some reason but can't tell why from the picture.

-Mike

**Comment by taismith123** [comment]
@claesmk Thanks for responding! I have actually just figured out my issue and now I am trying to create a pull request.
