### ISSUE TITLE
Team NULL: Implement Scanning Threat Detection

### ISSUE THREAD

**Issue by lancenonce** [NCATComp410/comp410_spring_2021#75]
NMAP Info: https://nmap.org/book/man-port-specification.html
Port Scan info: https://www.cisco.com/c/en/us/support/docs/security/asa-5500-x-series-next-generation-firewalls/113685-asa-threat-detection.html#anc13

Implement Detection for %ASA-4-733101: Object objectIP (is targeted|is attacking). Current burst rate is rate_val per second, max configured rate is rate_val ; Current average rate is rate_val per second, max configured rate is rate_val ; Cumulative total count is total_cnt.

**Comment by lancenonce** [comment]
@claesmk can I get a 1:1 with you tomorrow (3/23) somewhere between 4:30 and 6:30 if possible? I just finished the code for my Parse function, but I can't test it because I don't have the `id_pkg` library on my py39 for some reason. I would like to troubleshoot with you and also ask you some questions about whether I'm doing the project right so far! Thanks!

**Comment by claesmk** [comment]
5:30 tonight will work for me.  Will get you a zoom link later today.

**Comment by lancenonce** [comment]
Thank you!

Lance N. Davis

**Comment by lancenonce** [comment]
#79
